security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            provider: user_provider
            form_login:
                login_path: login
                default_target_path: dashboard
            logout:
                path: logout
                target: home


    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/user, roles: ROLE_USER }
