security:
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\Admin:
            algorithm: auto


    providers:
        user_provider:
            id: App\Security\UserProvider
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        level_one:
            pattern: ^/
            anonymous: true
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
            provider: user_provider
            form_login:
                login_path: login
                default_target_path: dashboard
            logout:
                path: logout
                target: home


    access_control:
         - { path: ^/user, roles: ROLE_USER }
